# @package agent
_target_: agent.crl.CRLAgent
name: crl
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later, overrwrite this when you need for the state encoder
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_wandb: ${use_wandb}
num_expl_steps: 2000 # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 1024 # 256 for pixels
init_critic: true
update_encoder: ${update_encoder}
skill_dim: 0
temp: 0.07
entropy_coef: 0
latent_size: 64
objective: SimClr
update_skill_every_step: 50
